import React, { useMemo, useState } from 'react';
import { Bell, CheckCircle2, ChevronRight, CircleAlert, Cloud, ExternalLink, Github, KeyRound, LockKeyhole, Mail, MessageCircle, RefreshCw, Settings, ShieldCheck } from 'lucide-react';
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Select } from '@/components/ui';
import { INITIAL_INTEGRATIONS, SETTINGS_TABS, type Integration, type SettingsTab, connectionAuditEntry, toggleIntegration } from '@/lib/settings-workspace';

const icons = { github: Github, render: Cloud, vercel: Cloud, netlify: Cloud, telegram: MessageCircle, email: Mail };
const variant = (status: Integration['status']) => status === 'connected' ? 'success' as const : 'neutral' as const;

export default function SettingsPage() {
  const [tab, setTab] = useState<SettingsTab>('General');
  const [integrations, setIntegrations] = useState(INITIAL_INTEGRATIONS);
  const [audit, setAudit] = useState(['Permission policy reviewed · production write actions require approval', 'Credential Vault reference verified · values remain sealed']);
  const [notice, setNotice] = useState('All configuration is governed by the Permission Engine.');
  const connected = useMemo(() => integrations.filter((item) => item.status === 'connected').length, [integrations]);
  const log = (entry: string) => setAudit((items) => [entry, ...items].slice(0, 5));
  const toggle = (item: Integration) => { const status = item.status === 'connected' ? 'disconnected' : 'connected'; setIntegrations((items) => toggleIntegration(items, item.id)); log(connectionAuditEntry(item, status)); setNotice(`${item.name} is ${status}. No credential values were displayed.`); };
  const test = (item: Integration) => { log(connectionAuditEntry(item, 'tested')); setNotice(`${item.name} connection check queued through Credential Vault.`); };
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 border-b border-border pb-5 lg:flex-row lg:items-end lg:justify-between"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-border bg-surface-muted text-primary"><Settings className="h-5 w-5" /></div><div><h1 className="text-2xl font-bold tracking-tight">Settings</h1><p className="mt-1 text-sm text-muted-foreground">Workspace controls, guarded integrations, and security policies.</p></div></div><Badge variant="success" withDot>{connected} integrations connected</Badge></header>
    <div className="flex gap-1 overflow-x-auto border-b border-border" role="tablist" aria-label="Settings sections">{SETTINGS_TABS.map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`shrink-0 border-b-2 px-3 py-2.5 text-sm font-medium transition-colors ${tab === item ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}>{item}</button>)}</div>
    {tab === 'General' && <General />}
    {tab === 'Integrations' && <Integrations items={integrations} audit={audit} onToggle={toggle} onTest={test} />}
    {tab === 'Security' && <Permissions onAudit={() => log('Permission policy reviewed · audit trail retained')} />}
    <div role="status" className="flex items-center gap-2 rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 shrink-0 text-primary" />{notice}</div>
  </div>;
}

function General() { return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_320px]"><Card><CardHeader><CardTitle>Workspace defaults</CardTitle><CardDescription>Set the operational context used by new runs and approvals.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Workspace name"><Input defaultValue="AgentOps" /></Field><Field label="Default environment"><Select defaultValue="staging"><option value="development">Development</option><option value="staging">Staging</option><option value="production">Production</option></Select></Field><Field label="Time zone"><Select defaultValue="utc"><option value="utc">UTC</option><option value="local">Local time</option></Select></Field><Field label="Run retention"><Select defaultValue="30"><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></Select></Field><div className="sm:col-span-2 flex justify-end"><Button leftIcon={<CheckCircle2 className="h-4 w-4" />}>Save workspace defaults</Button></div></CardContent></Card><Security /></div>; }

function Integrations({ items, audit, onToggle, onTest }: { items: Integration[]; audit: string[]; onToggle: (item: Integration) => void; onTest: (item: Integration) => void }) { return <div className="space-y-4"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => { const Icon = icons[item.id]; const connected = item.status === 'connected'; return <Card key={item.id} className="flex flex-col"><CardHeader><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2.5"><span className="rounded-lg border border-border bg-surface-muted p-2 text-primary"><Icon className="h-4 w-4" /></span><div><CardTitle>{item.name}</CardTitle><CardDescription className="mt-1">{item.description}</CardDescription></div></div><Badge variant={variant(item.status)} withDot>{item.status}</Badge></div></CardHeader><CardContent className="flex flex-1 flex-col gap-4"><div className="rounded-md border border-border bg-surface-muted/40 p-3"><p className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">Credential Vault</p><p className="mt-1 truncate font-mono text-xs text-foreground" title={item.secretRef}>secret_ref: {item.secretRef}</p><p className="mt-1 text-[11px] text-muted-foreground">Reference only — secret value is sealed.</p></div><div className="flex flex-wrap gap-1.5">{item.permissions.map((permission) => <Badge key={permission} variant="outline">{permission}</Badge>)}</div><div className="mt-auto flex flex-wrap gap-2"><Button size="sm" variant={connected ? 'outline' : 'primary'} onClick={() => onToggle(item)}>{connected ? 'Disconnect' : 'Connect'}</Button><Button size="sm" variant="ghost" onClick={() => onTest(item)} leftIcon={<RefreshCw className="h-3.5 w-3.5" />}>Test Connection</Button></div></CardContent></Card>; })}</div><Audit items={audit} /></div>; }

function Permissions({ onAudit }: { onAudit: () => void }) { return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Permission Engine</CardTitle><CardDescription>High-impact actions always require an explicit approval.</CardDescription></CardHeader><CardContent className="space-y-3">{[['Repository read', 'Allowed'], ['Create pull requests', 'Approval required'], ['Production deployment', 'Approval required'], ['Credential export', 'Denied']].map(([action, state]) => <div key={action} className="flex items-center justify-between rounded-lg border border-border bg-surface-muted/30 p-3"><span className="text-sm font-medium">{action}</span><Badge variant={state === 'Allowed' ? 'success' : state === 'Denied' ? 'danger' : 'warning'}>{state}</Badge></div>)}<Button variant="outline" onClick={onAudit} leftIcon={<ShieldCheck className="h-4 w-4" />}>Review policy</Button></CardContent></Card><Security /></div>; }
function Credentials() { return <Card><CardHeader><CardTitle>Credential Vault</CardTitle><CardDescription>Connections retain references only. Values are never rendered or emitted to client logs.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{['github/primary', 'render/primary', 'email/notifications'].map((ref) => <div key={ref} className="rounded-lg border border-border bg-surface-muted/30 p-4"><KeyRound className="h-4 w-4 text-primary" /><p className="mt-3 font-mono text-xs">secret_ref: vault://integrations/{ref}</p><Badge className="mt-2" variant="success" withDot>Sealed</Badge></div>)}</CardContent></Card>; }
function Notifications() { return <Card><CardHeader><CardTitle>Notifications</CardTitle><CardDescription>Choose which guarded events need attention.</CardDescription></CardHeader><CardContent className="space-y-3">{['Approval requests', 'Failed connection checks', 'Production deployment status'].map((label) => <label key={label} className="flex cursor-pointer items-center justify-between rounded-lg border border-border p-3 text-sm"><span className="flex items-center gap-2"><Bell className="h-4 w-4 text-primary" />{label}</span><input type="checkbox" defaultChecked className="h-4 w-4 accent-[var(--primary)]" /></label>)}</CardContent></Card>; }
function Security() { return <Card className="h-fit"><CardHeader><CardTitle>Security posture</CardTitle><CardDescription>Guardrails active for this workspace.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex gap-2 text-xs"><LockKeyhole className="h-4 w-4 shrink-0 text-success" />Credential values stay in the vault.</div><div className="flex gap-2 text-xs"><CircleAlert className="h-4 w-4 shrink-0 text-warning" />Writes require the Permission Engine.</div><div className="flex gap-2 text-xs"><ExternalLink className="h-4 w-4 shrink-0 text-primary" />Every integration event is audited.</div></CardContent></Card>; }
function Audit({ items }: { items: string[] }) { return <Card><CardHeader><CardTitle>Integration audit log</CardTitle><CardDescription>References and event outcomes only; no secret values are logged.</CardDescription></CardHeader><CardContent className="space-y-2">{items.map((item, index) => <div key={`${item}-${index}`} className="flex gap-2 rounded-md border border-border bg-surface-muted/30 p-2.5 text-xs text-muted-foreground"><ChevronRight className="h-3.5 w-3.5 shrink-0 text-primary" />{item}</div>)}</CardContent></Card>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-1.5"><span className="text-xs font-medium text-foreground">{label}</span>{children}</label>; }
