import React, { useEffect, useMemo, useState } from 'react';
import { usePathname, Link } from '@/lib/router';
import { api, type ApiRun } from '@/lib/api';
import { Badge, Button, Card, Input } from '@/components/ui';
import { ArrowLeft, AlertCircle, FileBarChart, FileText, Loader2, Search } from 'lucide-react';

type RunReport = ApiRun & { passRate: number; passed: number; failed: number; total: number };
const toReport = (run: ApiRun): RunReport => {
  const results = run.testResults ?? [];
  const passed = results.filter(r => r.status === 'passed').length;
  const failed = results.filter(r => ['failed','error'].includes(r.status)).length;
  const total = results.length;
  return { ...run, passed, failed, total, passRate: total ? Math.round((passed / total) * 100) : 0 };
};

export default function ReportsPage(){const id=usePathname().split('/').filter(Boolean)[1];return id?<ReportDetail id={id}/>:<ReportList/>;}
function ReportList(){const [reports,setReports]=useState<RunReport[]>([]);const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);useEffect(()=>{api.listRuns().then(async r=>{const details=await Promise.all(r.data.slice(0,25).map(run=>api.getRun(run.id).then(x=>x.data).catch(()=>run)));setReports(details.map(toReport));}).catch(e=>setError(e instanceof Error?e.message:'Failed to load reports')).finally(()=>setLoading(false));},[]);const filtered=useMemo(()=>reports.filter(r=>!q.trim()||r.id.toLowerCase().includes(q.toLowerCase())||r.status.includes(q.toLowerCase())),[reports,q]);return <div className="space-y-6"><div className="border-b border-border pb-3"><div className="flex gap-2 items-center"><FileBarChart className="w-5 h-5 text-primary"/><h1 className="text-2xl font-bold">Reports</h1></div><p className="text-sm text-muted-foreground mt-1">Run summaries generated from real Phase-1 results.</p></div><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reports..." leftIcon={<Search className="w-4 h-4"/>}/>{loading?<State text="Loading reports..." icon={<Loader2 className="animate-spin"/>}/>:error?<State text={error} icon={<AlertCircle/>}/>:filtered.length===0?<State text="No run reports yet."/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(r=><Link href={`/reports/${r.id}`} key={r.id} className="p-4 rounded-xl border border-border bg-surface hover:border-primary/30"><div className="flex items-start justify-between gap-2"><FileText className="w-5 h-5 text-primary"/><Badge variant={r.status==='passed'||r.status==='completed'?'success':['failed','error','aborted'].includes(r.status)?'danger':r.status==='running'?'info':'neutral'}>{r.status}</Badge></div><p className="font-mono text-xs mt-4 truncate">{r.id}</p><div className="grid grid-cols-3 gap-2 mt-4 text-center"><Stat label="Pass rate" value={`${r.passRate}%`}/><Stat label="Passed" value={String(r.passed)}/><Stat label="Failed" value={String(r.failed)}/></div></Link>)}</div>}</div>}
function ReportDetail({id}:{id:string}){const [report,setReport]=useState<RunReport|null>(null);const [error,setError]=useState<string|null>(null);useEffect(()=>{api.getRun(id).then(r=>setReport(toReport(r.data))).catch(e=>setError(e instanceof Error?e.message:'Failed to load report'));},[id]);if(error)return <State text={error} icon={<AlertCircle/>}/>;if(!report)return <State text="Loading report..." icon={<Loader2 className="animate-spin"/>}/>;return <div className="space-y-6"><Link href="/reports"><Button variant="ghost" size="sm" leftIcon={<ArrowLeft className="w-4 h-4"/>}>Back to Reports</Button></Link><div><h1 className="text-2xl font-bold">QA Run Report</h1><p className="font-mono text-xs text-muted-foreground mt-1">{report.id}</p></div><Card className="p-5 grid sm:grid-cols-4 gap-4"><Stat label="Pass rate" value={`${report.passRate}%`}/><Stat label="Tests" value={String(report.total)}/><Stat label="Passed" value={String(report.passed)}/><Stat label="Failed" value={String(report.failed)}/></Card><Card className="p-5"><h2 className="font-semibold mb-3">Summary</h2><p className="text-sm text-muted-foreground">Run status: {report.status}. {report.issues?.length ?? 0} issue(s) and {report.evidence?.length ?? 0} evidence item(s) recorded.</p><div className="mt-4 flex gap-2"><Link href={`/runs/${report.id}`}><Button size="sm" variant="outline">Open Run</Button></Link></div></Card></div>}
function Stat({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-bold font-mono mt-1">{value}</p></div>}
function State({text,icon}:{text:string;icon?:React.ReactNode}){return <div className="py-12 text-center text-muted-foreground flex items-center justify-center gap-2">{icon}{text}</div>}
