import React, { useEffect, useState } from 'react';
import { BrainCircuit, ShieldCheck, Activity, RefreshCw, MessageSquareText, Bot } from 'lucide-react';
import { Badge, Button, Card, CardContent } from '@/components/ui';
import { api, type ApiCommunicationLog, type ApiSpecialistAgent } from '@/lib/api';

function variant(level: ApiSpecialistAgent['permission']) { return level === 'Green' ? 'success' as const : level === 'Yellow' ? 'warning' as const : 'danger' as const; }
function ago(value: string | null) { if (!value) return 'No activity recorded'; const m = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return m < 1 ? 'just now' : m < 60 ? `${m}m ago` : `${Math.floor(m / 60)}h ago`; }

export default function AgentPage() {
  const [agents, setAgents] = useState<ApiSpecialistAgent[]>([]); const [log, setLog] = useState<ApiCommunicationLog[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [a, l] = await Promise.all([api.listAgents(), api.listAgentCommunications()]); setAgents(a.data); setLog(l.data); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <div className="space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-border pb-5 sm:flex-row sm:items-end"><div className="flex items-start gap-3"><span className="rounded-lg border border-primary/25 bg-primary/10 p-2 text-primary"><BrainCircuit className="h-6 w-6" /></span><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Orchestration</p><h1 className="mt-1 text-2xl font-bold tracking-tight">AI Agent Control Room</h1><p className="mt-1 text-sm text-muted-foreground">Chief of Staff routes commands, enforces permissions, and retrieves redacted operational memory.</p></div></div><Button variant="outline" size="sm" onClick={() => void load()} loading={loading} leftIcon={<RefreshCw className="h-3.5 w-3.5" />}>Refresh</Button></header>
    <Card className="border-primary/25 bg-primary/5"><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><span className="rounded-lg bg-primary/15 p-2 text-primary"><Bot className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="font-semibold">Chief of Staff</p><p className="mt-1 text-sm text-muted-foreground">The global AI chat is the master-agent interface. It assigns specialists, checks the Permission Engine, pauses risky work for human approval, and uses stored history for retrieval—not model training.</p></div><Badge variant="info" withDot>Central router</Badge></CardContent></Card>
    <section><div className="mb-3 flex items-center gap-2"><Activity className="h-4 w-4 text-primary" /><h2 className="font-semibold">Specialist agents</h2></div>{loading ? <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 10 }).map((_, i) => <div key={i} className="h-48 animate-pulse rounded-xl border border-border bg-surface-muted/40" />)}</div> : <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{agents.map((agent) => <Card key={agent.id}><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{agent.name}</h3><p className="mt-1 text-sm text-muted-foreground">{agent.capability}</p></div><Badge variant={agent.status === 'Active' ? 'info' : 'neutral'} withDot>{agent.status}</Badge></div><dl className="mt-5 space-y-3 text-sm"><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Permission level</dt><dd className="mt-1"><Badge variant={variant(agent.permission)}>{agent.permission}</Badge></dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Current task</dt><dd className="mt-1 line-clamp-2">{agent.currentTask || 'No task assigned'}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Last activity</dt><dd className="mt-1 text-muted-foreground">{ago(agent.lastActivity)}</dd></div></dl></CardContent></Card>)}</div>}</section>
    <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><Card><CardContent className="p-5"><div className="flex items-center gap-2"><MessageSquareText className="h-4 w-4 text-primary" /><h2 className="font-semibold">Communication log</h2></div><div className="mt-4 space-y-3">{log.length ? log.map((entry) => <article key={entry.id} className="border-l-2 border-primary/30 pl-3"><p className="text-xs font-medium">{entry.speaker} <span className="text-muted-foreground">→</span> {entry.recipient}</p><p className="mt-1 text-sm text-muted-foreground">{entry.message}</p><p className="mt-1 text-xs text-muted-foreground">{ago(entry.createdAt)}</p></article>) : <p className="text-sm text-muted-foreground">No stored communication yet. Use the global Chief of Staff chat to route work.</p>}</div></CardContent></Card><Card><CardContent className="p-5"><ShieldCheck className="h-5 w-5 text-primary" /><h2 className="mt-3 font-semibold">Safety and memory</h2><p className="mt-2 text-sm text-muted-foreground">Messages and memory are redacted before storage. Outcomes, approvals, preferences, successful fixes, and failure patterns are retrieved as context for future decisions.</p></CardContent></Card></section>
  </div>;
}
