import React, { useEffect, useMemo, useState } from 'react';
import { usePathname, Link } from '@/lib/router';
import { api, type ApiBrowserSession } from '@/lib/api';
import { Badge, Button, Card, Input } from '@/components/ui';
import { ArrowLeft, AlertCircle, Monitor, Search, Loader2 } from 'lucide-react';

const statusVariant = (status: ApiBrowserSession['status']) => status === 'active' ? 'info' : status === 'crashed' ? 'danger' : 'success';
export default function BrowserSessionsPage(){const id=usePathname().split('/').filter(Boolean)[1];return id?<SessionDetail id={id}/>:<SessionList/>;}
function SessionList(){const [items,setItems]=useState<ApiBrowserSession[]>([]);const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);useEffect(()=>{api.listSessions().then(r=>setItems(r.data)).catch(e=>setError(e instanceof Error?e.message:'Failed to load sessions')).finally(()=>setLoading(false));},[]);const filtered=useMemo(()=>items.filter(s=>!q.trim()||s.id.toLowerCase().includes(q.toLowerCase())||s.runId.toLowerCase().includes(q.toLowerCase())),[items,q]);return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border pb-3"><div><div className="flex gap-2 items-center"><Monitor className="w-5 h-5 text-primary"/><h1 className="text-2xl font-bold">Browser Sessions</h1></div><p className="text-sm text-muted-foreground mt-1">Sessions created by the backend browser engine.</p></div><Link href="/command"><Button size="sm">New QA Session</Button></Link></div><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search sessions..." leftIcon={<Search className="w-4 h-4"/>}/>{loading?<State text="Loading sessions..." icon={<Loader2 className="animate-spin"/>}/>:error?<State text={error} icon={<AlertCircle/>}/>:filtered.length===0?<State text="No browser sessions yet."/>:<div className="border border-border rounded-xl overflow-x-auto bg-surface"><table className="w-full text-sm"><thead><tr className="text-left text-xs bg-surface-muted text-muted-foreground"><th className="p-3">Session</th><th className="p-3">Run</th><th className="p-3">Status</th><th className="p-3">Started</th><th className="p-3"></th></tr></thead><tbody>{filtered.map(s=><tr key={s.id} className="border-t border-border"><td className="p-3 font-mono text-xs">{s.id}</td><td className="p-3 font-mono text-xs"><Link className="text-primary" href={`/runs/${s.runId}`}>{s.runId}</Link></td><td className="p-3"><Badge variant={statusVariant(s.status)}>{s.status}</Badge></td><td className="p-3 text-xs text-muted-foreground">{new Date(s.startedAt).toLocaleString()}</td><td className="p-3 text-right"><Link href={`/sessions/${s.id}`}><Button variant="ghost" size="sm">Details</Button></Link></td></tr>)}</tbody></table></div>}</div>}
function SessionDetail({id}:{id:string}){const [session,setSession]=useState<ApiBrowserSession|null>(null);const [error,setError]=useState<string|null>(null);useEffect(()=>{api.getSession(id).then(r=>setSession(r.data)).catch(e=>setError(e instanceof Error?e.message:'Failed to load session'));},[id]);if(error)return <State text={error} icon={<AlertCircle/>}/>;if(!session)return <State text="Loading session..." icon={<Loader2 className="animate-spin"/>}/>;return <div className="space-y-6"><Link href="/sessions"><Button variant="ghost" size="sm" leftIcon={<ArrowLeft className="w-4 h-4"/>}>Back to Sessions</Button></Link><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold">Browser Session</h1><Badge variant={statusVariant(session.status)}>{session.status}</Badge></div><p className="font-mono text-xs text-muted-foreground mt-1">{session.id}</p></div><Card className="p-5 grid sm:grid-cols-2 gap-4 text-sm"><div><span className="text-xs text-muted-foreground">Run</span><p><Link className="font-mono text-primary" href={`/runs/${session.runId}`}>{session.runId}</Link></p></div><div><span className="text-xs text-muted-foreground">Started</span><p>{new Date(session.startedAt).toLocaleString()}</p></div><div><span className="text-xs text-muted-foreground">Ended</span><p>{session.endedAt?new Date(session.endedAt).toLocaleString():'—'}</p></div></Card></div>}
function State({text,icon}:{text:string;icon?:React.ReactNode}){return <div className="py-12 text-center text-muted-foreground flex items-center justify-center gap-2">{icon}{text}</div>}
