import React, { useEffect, useState } from 'react';
import { Monitor, Play, Pause, History, RefreshCw, ShieldCheck } from 'lucide-react';
import { api, type ApiBrowserSession } from '@/lib/api';
import { Badge, Button, Card, CardContent } from '@/components/ui';
import { Link } from '@/lib/router';

function variant(status: ApiBrowserSession['status']) { return status === 'active' ? 'info' as const : status === 'closed' ? 'success' as const : 'danger' as const; }
function schedule(session: ApiBrowserSession) { return session.status === 'active' ? 'Running now' : 'On demand'; }

export default function BrowserWorkersPage() {
  const [workers, setWorkers] = useState<ApiBrowserSession[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setWorkers((await api.listSessions()).data); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <div className="space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-border pb-5 sm:flex-row sm:items-end"><div className="flex items-start gap-3"><span className="rounded-lg border border-primary/25 bg-primary/10 p-2 text-primary"><Monitor className="h-6 w-6" /></span><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Autonomous browsing</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Browser Workers</h1><p className="mt-1 text-sm text-muted-foreground">Real browser execution sessions, evidence, console/network diagnostics, and regression history.</p></div></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => void load()} loading={loading} leftIcon={<RefreshCw className="h-3.5 w-3.5" />}>Refresh</Button><Link href="/command"><Button size="sm" leftIcon={<Play className="h-3.5 w-3.5" />}>Run Now</Button></Link></div></header>
    <Card className="border-primary/25 bg-primary/5"><CardContent className="flex items-start gap-3 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p className="text-sm text-muted-foreground">Workers use the Credential Vault’s secret references only. Credentials are never returned to the UI, browser history, evidence, logs, notifications, or Chief of Staff chat.</p></CardContent></Card>
    {loading ? <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, i) => <div key={i} className="h-64 animate-pulse rounded-xl border border-border bg-surface-muted/40" />)}</div> : workers.length === 0 ? <Card><CardContent className="py-14 text-center"><p className="font-medium">No Browser Workers yet</p><p className="mt-2 text-sm text-muted-foreground">Dispatch a QA run to create a backend browser worker and its retained evidence.</p></CardContent></Card> : <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{workers.map((worker) => <Card key={worker.id}><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">Browser Worker</p><p className="mt-1 font-mono text-xs text-muted-foreground">{worker.id}</p></div><Badge variant={variant(worker.status)} withDot>{worker.status}</Badge></div><dl className="mt-5 space-y-3 text-sm"><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Project / app</dt><dd className="mt-1 font-mono text-xs">Run {worker.runId}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Schedule</dt><dd className="mt-1">{schedule(worker)}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Current action</dt><dd className="mt-1 text-muted-foreground">{worker.status === 'active' ? 'Executing browser checks' : 'Waiting for dispatch'}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Last run</dt><dd className="mt-1 text-muted-foreground">{new Date(worker.startedAt).toLocaleString()}</dd></div></dl><div className="mt-5 flex gap-2 border-t border-border pt-4"><Link href={`/sessions/${worker.id}`}><Button size="sm" variant="outline" leftIcon={<History className="h-3.5 w-3.5" />}>View History</Button></Link>{worker.status === 'active' && <Link href={`/runs/${worker.runId}`}><Button size="sm" variant="ghost" leftIcon={<Pause className="h-3.5 w-3.5" />}>Pause</Button></Link>}</div></CardContent></Card>)}</div>}
  </div>;
}
