import React, { useEffect, useRef, useState } from 'react';
import { Bot, CheckCircle2, GripHorizontal, Maximize2, MessageSquareText, Minimize2, Send, ShieldAlert, X } from 'lucide-react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { Badge, Button, Textarea } from '@/components/ui';
import { api, type ApiCommandChatResult } from '@/lib/api';
import { usePathname, useRouter } from '@/lib/router';

type Message = { id: string; role: 'user' | 'agent'; text: string; result?: ApiCommandChatResult };

export function GlobalCommandChat() {
  const pathname = usePathname(); const router = useRouter(); const reduceMotion = useReducedMotion();
  const [open, setOpen] = useState(false); const [minimized, setMinimized] = useState(false); const [prompt, setPrompt] = useState('');
  const [messages, setMessages] = useState<Message[]>([{ id: 'welcome', role: 'agent', text: 'I am the Chief of Staff. Ask me to route QA, code, GitHub, deployment, security, database, email, calendar, or messaging work. Permission checks and redacted memory are included automatically.' }]);
  const [loading, setLoading] = useState(false); const [size, setSize] = useState({ width: 400, height: 580 }); const [offset, setOffset] = useState({ x: 0, y: 0 });
  const dragStart = useRef<{ x: number; y: number; ox: number; oy: number } | null>(null); const resizeStart = useRef<{ x: number; y: number; width: number; height: number } | null>(null);
  const runId = /^\/runs\/([^/]+)/.exec(pathname)?.[1];
  useEffect(() => { const move = (event: PointerEvent) => { if (dragStart.current) setOffset({ x: dragStart.current.ox + event.clientX - dragStart.current.x, y: dragStart.current.oy + event.clientY - dragStart.current.y }); if (resizeStart.current) setSize({ width: Math.min(720, Math.max(320, resizeStart.current.width + resizeStart.current.x - event.clientX)), height: Math.min(760, Math.max(360, resizeStart.current.height + resizeStart.current.y - event.clientY)) }); }; const stop = () => { dragStart.current = null; resizeStart.current = null; }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop); return () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); }; }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const command = prompt.trim(); if (!command || loading) return; setPrompt(''); setLoading(true); setMessages((all) => [...all, { id: crypto.randomUUID(), role: 'user', text: command }]); try { const response = await api.dispatchCommandChat(command, { page: pathname, runId }); const result = response.data; setMessages((all) => [...all, { id: crypto.randomUUID(), role: 'agent', text: result.summary, result }]); } catch { setMessages((all) => [...all, { id: crypto.randomUUID(), role: 'agent', text: 'The command service is unavailable. Your command was not executed; no credentials were sent or displayed.' }]); } finally { setLoading(false); } };
  return <>
    <button type="button" aria-label="Open AI Command Chat" onClick={() => { setOpen(true); setMinimized(false); }} className="fixed bottom-5 right-5 z-40 flex h-12 w-12 items-center justify-center rounded-full border border-primary/30 bg-primary text-primary-foreground shadow-lg transition-transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus"><MessageSquareText className="h-5 w-5" /></button>
    <AnimatePresence>{open && <motion.section role="dialog" aria-label="AI Command Chat" initial={reduceMotion ? false : { opacity: 0, x: 32 }} animate={{ opacity: 1, x: 0 }} exit={reduceMotion ? undefined : { opacity: 0, x: 32 }} transition={{ duration: 0.18 }} style={{ width: minimized ? 300 : size.width, height: minimized ? 'auto' : size.height, transform: `translate(${offset.x}px, ${offset.y}px)` }} className="fixed bottom-5 right-5 z-50 flex max-w-[calc(100vw-2rem)] flex-col overflow-hidden rounded-xl border border-border bg-surface shadow-2xl">
      <header onPointerDown={(event) => { if ((event.target as HTMLElement).closest('button')) return; dragStart.current = { x: event.clientX, y: event.clientY, ox: offset.x, oy: offset.y }; }} className="flex cursor-move items-center justify-between border-b border-border bg-surface-muted/70 px-3 py-2.5"><div className="flex items-center gap-2"><span className="rounded-md bg-primary/10 p-1.5 text-primary"><Bot className="h-4 w-4" /></span><div><p className="text-sm font-semibold">Chief of Staff</p><p className="text-[10px] text-muted-foreground">Context: {runId ? `run ${runId}` : pathname}</p></div></div><div className="flex items-center gap-1"><Button size="icon" variant="ghost" aria-label={minimized ? 'Expand chat' : 'Minimize chat'} onClick={() => setMinimized((value) => !value)}>{minimized ? <Maximize2 className="h-4 w-4" /> : <Minimize2 className="h-4 w-4" />}</Button><Button size="icon" variant="ghost" aria-label="Close chat" onClick={() => setOpen(false)}><X className="h-4 w-4" /></Button></div></header>
      {!minimized && <><div className="flex-1 space-y-3 overflow-y-auto p-3" aria-live="polite">{messages.map((message) => <article key={message.id} className={`rounded-lg border p-3 text-xs ${message.role === 'user' ? 'ml-8 border-primary/20 bg-primary/5' : 'mr-4 border-border bg-surface-muted/35'}`}><p className="mb-1 font-mono text-[10px] uppercase text-muted-foreground">{message.role === 'user' ? 'You' : 'AgentOps'}</p><p className="leading-relaxed">{message.text}</p>{message.result && <div className="mt-3 space-y-2 border-t border-border pt-2"><Badge variant={message.result.status === 'approval_required' ? 'warning' : message.result.status === 'blocked' ? 'danger' : 'success'}>{message.result.status === 'approval_required' ? 'Human approval required' : message.result.permission.tier + ' tier'}</Badge>{message.result.progress.map((step) => <div key={step} className="flex gap-1.5 text-[11px] text-muted-foreground"><CheckCircle2 className="h-3.5 w-3.5 shrink-0 text-primary" />{step}</div>)}{message.result.status === 'ready' && <Button size="sm" variant="outline" onClick={() => router.push(message.result!.destination)}>Open {message.result.intent} tool</Button>}{message.result.approval && <div className="flex gap-1.5 text-[11px] text-warning"><ShieldAlert className="h-3.5 w-3.5 shrink-0" />Approval {message.result.approval.approvalId} is pending.</div>}</div>}</article>)}{loading && <div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="h-2 w-2 animate-pulse rounded-full bg-primary" />Parsing intent and checking permissions…</div>}</div><form onSubmit={submit} className="border-t border-border p-3"><Textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={2} placeholder="Ask AgentOps to take action…" aria-label="AI command" /><div className="mt-2 flex items-center justify-between gap-2"><span className="text-[10px] text-muted-foreground">Secrets are redacted from chat and audit logs.</span><Button size="sm" type="submit" disabled={!prompt.trim() || loading} leftIcon={<Send className="h-3.5 w-3.5" />}>Send</Button></div></form><span onPointerDown={(event) => { resizeStart.current = { x: event.clientX, y: event.clientY, width: size.width, height: size.height }; }} className="absolute bottom-0 left-0 cursor-sw-resize p-1 text-muted-foreground"><GripHorizontal className="h-4 w-4 rotate-45" /></span></>}</motion.section>}</AnimatePresence>
  </>;
}
