import { BrowserSession, ExecutionStageName, StageInfo } from '@/types';

export const EXECUTION_STAGE_NAMES: ExecutionStageName[] = [
  'Understanding',
  'Planning',
  'Launching Browser',
  'Exploring',
  'Testing',
  'Analyzing',
  'Complete',
];

export const PREVIEW_SESSIONS: BrowserSession[] = [
  {
    id: 'ses_live_1048',
    targetUrl: 'https://ecommerce.example.com/checkout',
    targetHost: 'ecommerce.example.com',
    prompt: 'Add an item to the shopping cart, proceed through the checkout steps, fill in test billing details, and verify order summary calculations before triggering final confirmation.',
    status: 'running',
    currentStage: 'Testing',
    startedAt: '2 mins ago',
    duration: '1m 48s',
    viewport: {
      width: 1280,
      height: 800,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 HeadlessChrome/124.0.0.0 Safari/537.36 AgentOps/1.0',
    },
    stages: [
      {
        name: 'Understanding',
        state: 'completed',
        duration: '2.1s',
        description: 'Parsed objective: Checkout funnel assertion & payment gateway validation.',
      },
      {
        name: 'Planning',
        state: 'completed',
        duration: '3.4s',
        description: 'Synthesized 5-step interactive test graph across cart, billing, and review.',
      },
      {
        name: 'Launching Browser',
        state: 'completed',
        duration: '4.8s',
        description: 'Spawned isolated Chromium instance with clean cookies and 1280x800 viewport.',
      },
      {
        name: 'Exploring',
        state: 'completed',
        duration: '14.2s',
        description: 'Discovered DOM route /checkout, form fields, and payment iframe tokens.',
      },
      {
        name: 'Testing',
        state: 'active',
        duration: 'Running...',
        description: 'Executing step 4 of 5: Interacting with shipping form and verifying price totals.',
      },
      {
        name: 'Analyzing',
        state: 'pending',
        description: 'Aggregating console telemetry, HTTP status codes, and DOM snapshots.',
      },
      {
        name: 'Complete',
        state: 'pending',
        description: 'Generating final test artifact summary and defect classification.',
      },
    ],
    events: [
      {
        id: 'evt_101',
        timestamp: '10:14:02',
        relativeTime: '00:02',
        type: 'system',
        description: 'Initialized AgentOps browser environment (Chromium 124.0, Viewport 1280x800).',
        status: 'info',
      },
      {
        id: 'evt_102',
        timestamp: '10:14:06',
        relativeTime: '00:06',
        type: 'navigation',
        description: 'Navigated to https://ecommerce.example.com/checkout',
        status: 'success',
        details: { url: 'https://ecommerce.example.com/checkout' },
      },
      {
        id: 'evt_103',
        timestamp: '10:14:12',
        relativeTime: '00:12',
        type: 'assertion',
        description: 'Asserted document.title equals "Checkout | ModernStore"',
        status: 'success',
      },
      {
        id: 'evt_104',
        timestamp: '10:14:18',
        relativeTime: '00:18',
        type: 'input',
        description: 'Typed "alex.dev@example.com" into input[name="email"]',
        status: 'success',
        details: { selector: 'input[name="email"]', value: 'alex.dev@example.com' },
      },
      {
        id: 'evt_105',
        timestamp: '10:14:24',
        relativeTime: '00:24',
        type: 'input',
        description: 'Typed "Alex Mercer" into input[name="fullName"]',
        status: 'success',
        details: { selector: 'input[name="fullName"]', value: 'Alex Mercer' },
      },
      {
        id: 'evt_106',
        timestamp: '10:14:31',
        relativeTime: '00:31',
        type: 'click',
        description: 'Clicked button#select-standard-shipping',
        status: 'success',
        details: { selector: 'button#select-standard-shipping' },
      },
      {
        id: 'evt_107',
        timestamp: '10:14:35',
        relativeTime: '00:35',
        type: 'screenshot',
        description: 'Captured visual evidence snapshot #1 (Shipping form completed)',
        status: 'info',
      },
      {
        id: 'evt_108',
        timestamp: '10:14:40',
        relativeTime: '00:40',
        type: 'console',
        description: 'Console warning detected: Third-party analytics script took >850ms to execute.',
        status: 'warning',
        details: { message: '[Analytics] Slow tag evaluation on checkout entry' },
      },
      {
        id: 'evt_109',
        timestamp: '10:14:55',
        relativeTime: '00:55',
        type: 'assertion',
        description: 'Asserted order subtotal $129.00 + shipping $12.00 equals $141.00',
        status: 'success',
      },
      {
        id: 'evt_110',
        timestamp: '10:15:10',
        relativeTime: '01:10',
        type: 'network',
        description: 'POST /api/v1/payment/verify-token completed with HTTP 402 (Payment Required)',
        status: 'error',
        details: { url: '/api/v1/payment/verify-token', code: '402' },
      },
      {
        id: 'evt_111',
        timestamp: '10:15:20',
        relativeTime: '01:20',
        type: 'click',
        description: 'Agent focused on input[data-testid="card-number"] for re-attempt validation',
        status: 'info',
        details: { selector: 'input[data-testid="card-number"]' },
      },
    ],
    consoleLogs: [
      {
        id: 'c_1',
        timestamp: '10:14:07',
        level: 'info',
        source: 'checkout.bundle.js:42',
        message: 'Hydrated React root with 1 items in cart checkout session (id: cart_98213)',
      },
      {
        id: 'c_2',
        timestamp: '10:14:15',
        level: 'info',
        source: 'payment-sdk.js:18',
        message: 'Payment gateway iframe securely initialized into sandbox frame #stripe-elements',
      },
      {
        id: 'c_3',
        timestamp: '10:14:40',
        level: 'warning',
        source: 'vendor-analytics.js:210',
        message: 'Performance warning: Tag manager took 862ms. Consider deferring non-critical telemetry during checkout funnel.',
      },
      {
        id: 'c_4',
        timestamp: '10:15:10',
        level: 'error',
        source: 'api-client.ts:89',
        message: 'Uncaught (in promise) Error: Request failed with status 402 (Card declined / test token requires 3D Secure fallback)',
        stack: 'at ApiClient.post (api-client.ts:89)\n  at CheckoutProvider.handlePayment (checkout-provider.tsx:145)\n  at HTMLButtonElement.dispatch (react-dom.js:312)',
      },
    ],
    networkLogs: [
      {
        id: 'net_1',
        timestamp: '10:14:06',
        method: 'GET',
        url: '/checkout',
        status: 200,
        statusText: 'OK',
        duration: '142ms',
        size: '34.2 KB',
        type: 'document',
        hasError: false,
      },
      {
        id: 'net_2',
        timestamp: '10:14:07',
        method: 'GET',
        url: '/_next/static/chunks/checkout.js',
        status: 200,
        statusText: 'OK',
        duration: '88ms',
        size: '128.4 KB',
        type: 'script',
        hasError: false,
      },
      {
        id: 'net_3',
        timestamp: '10:14:09',
        method: 'GET',
        url: '/api/v1/cart/summary',
        status: 200,
        statusText: 'OK',
        duration: '65ms',
        size: '1.8 KB',
        type: 'fetch',
        hasError: false,
      },
      {
        id: 'net_4',
        timestamp: '10:14:32',
        method: 'POST',
        url: '/api/v1/shipping/calculate',
        status: 200,
        statusText: 'OK',
        duration: '190ms',
        size: '890 B',
        type: 'fetch',
        hasError: false,
      },
      {
        id: 'net_5',
        timestamp: '10:15:10',
        method: 'POST',
        url: '/api/v1/payment/verify-token',
        status: 402,
        statusText: 'Payment Required',
        duration: '340ms',
        size: '420 B',
        type: 'fetch',
        hasError: true,
      },
      {
        id: 'net_6',
        timestamp: '10:15:18',
        method: 'POST',
        url: '/api/v1/telemetry/event',
        status: 204,
        statusText: 'No Content',
        duration: '42ms',
        size: '0 B',
        type: 'beacon',
        hasError: false,
      },
    ],
    evidence: [
      {
        id: 'ev_1',
        title: 'Initial Cart & Customer Identification',
        timestamp: '10:14:10',
        stepNumber: 1,
        stepName: 'Cart Discovery',
        type: 'screenshot',
        caption: 'Agent verified checkout container visibility and customer credentials form.',
        mockPreviewType: 'checkout_step',
        highlightSelector: 'form#checkout-contact',
      },
      {
        id: 'ev_2',
        title: 'Shipping Calculation & Subtotal Match',
        timestamp: '10:14:35',
        stepNumber: 2,
        stepName: 'Shipping Method Selection',
        type: 'screenshot',
        caption: 'Order summary calculation confirmed: Standard ground shipping ($12.00) applied.',
        mockPreviewType: 'cart_summary',
        highlightSelector: 'div.order-summary-box',
      },
      {
        id: 'ev_3',
        title: 'Payment Gateway Defect Evidence',
        timestamp: '10:15:12',
        stepNumber: 4,
        stepName: 'Token Verification Error',
        type: 'screenshot',
        caption: 'Captured visual error alert in payment card iframe after HTTP 402 rejection.',
        mockPreviewType: 'payment_error',
        highlightSelector: 'div.payment-error-alert',
      },
    ],
    stats: {
      totalActions: 11,
      assertionsPassed: 4,
      assertionsFailed: 1,
      consoleErrors: 1,
      networkErrors: 1,
    },
  },

  {
    id: 'ses_live_1045',
    targetUrl: 'https://staging.example.com/signup',
    targetHost: 'staging.example.com',
    prompt: 'Test the registration and login flows. Attempt signup with an invalid email format to verify form validation, then log in with test credentials and assert redirection to the onboarding workspace.',
    status: 'completed',
    currentStage: 'Complete',
    startedAt: '45 mins ago',
    duration: '3m 12s',
    viewport: {
      width: 1280,
      height: 800,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 HeadlessChrome/124.0.0.0 Safari/537.36 AgentOps/1.0',
    },
    stages: [
      { name: 'Understanding', state: 'completed', duration: '1.8s' },
      { name: 'Planning', state: 'completed', duration: '2.9s' },
      { name: 'Launching Browser', state: 'completed', duration: '3.5s' },
      { name: 'Exploring', state: 'completed', duration: '18.1s' },
      { name: 'Testing', state: 'completed', duration: '1m 45s' },
      { name: 'Analyzing', state: 'completed', duration: '42s' },
      { name: 'Complete', state: 'completed', duration: '18s' },
    ],
    events: [
      {
        id: 'evt_201',
        timestamp: '09:30:00',
        relativeTime: '00:00',
        type: 'system',
        description: 'Session initialized with target https://staging.example.com/signup',
        status: 'info',
      },
      {
        id: 'evt_202',
        timestamp: '09:30:08',
        relativeTime: '00:08',
        type: 'navigation',
        description: 'Navigated to registration form page',
        status: 'success',
      },
      {
        id: 'evt_203',
        timestamp: '09:30:15',
        relativeTime: '00:15',
        type: 'input',
        description: 'Inputted invalid email format "invalid-email" to test client validation',
        status: 'success',
      },
      {
        id: 'evt_204',
        timestamp: '09:30:22',
        relativeTime: '00:22',
        type: 'assertion',
        description: 'Asserted validation message "Please enter a valid email address" appears on blur',
        status: 'success',
      },
      {
        id: 'evt_205',
        timestamp: '09:30:45',
        relativeTime: '00:45',
        type: 'input',
        description: 'Inputted valid email "qa.agent@example.com" and secure password',
        status: 'success',
      },
      {
        id: 'evt_206',
        timestamp: '09:31:10',
        relativeTime: '01:10',
        type: 'click',
        description: 'Clicked button[type="submit"]',
        status: 'success',
      },
      {
        id: 'evt_207',
        timestamp: '09:31:30',
        relativeTime: '01:30',
        type: 'assertion',
        description: 'Asserted URL redirected to /onboarding/workspace with authenticated session cookie',
        status: 'success',
      },
    ],
    consoleLogs: [
      {
        id: 'c_201',
        timestamp: '09:30:09',
        level: 'info',
        source: 'app.js:55',
        message: 'Auth provider loaded: Local Cognito User Pool',
      },
    ],
    networkLogs: [
      {
        id: 'net_201',
        timestamp: '09:30:08',
        method: 'GET',
        url: '/signup',
        status: 200,
        statusText: 'OK',
        duration: '95ms',
        size: '18 KB',
        type: 'document',
        hasError: false,
      },
      {
        id: 'net_202',
        timestamp: '09:31:11',
        method: 'POST',
        url: '/api/v1/auth/signup',
        status: 201,
        statusText: 'Created',
        duration: '210ms',
        size: '1.2 KB',
        type: 'fetch',
        hasError: false,
      },
    ],
    evidence: [
      {
        id: 'ev_201',
        title: 'Authentication Form Validation State',
        timestamp: '09:30:25',
        stepNumber: 1,
        stepName: 'Email Validation Check',
        type: 'screenshot',
        caption: 'Inline email field error verified on malformed input string.',
        mockPreviewType: 'auth_dialog',
        highlightSelector: 'div.field-error',
      },
    ],
    stats: {
      totalActions: 18,
      assertionsPassed: 8,
      assertionsFailed: 0,
      consoleErrors: 0,
      networkErrors: 0,
    },
  },

  {
    id: 'ses_live_1042',
    targetUrl: 'https://api-app.example.com/dashboard',
    targetHost: 'api-app.example.com',
    prompt: 'Explore the telemetry dashboard, navigate to billing history, and verify pagination controls and export buttons.',
    status: 'failed',
    currentStage: 'Testing',
    startedAt: '3 hours ago',
    duration: '2m 05s',
    viewport: {
      width: 1280,
      height: 800,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 HeadlessChrome/124.0.0.0 Safari/537.36 AgentOps/1.0',
    },
    stages: [
      { name: 'Understanding', state: 'completed', duration: '2.0s' },
      { name: 'Planning', state: 'completed', duration: '3.1s' },
      { name: 'Launching Browser', state: 'completed', duration: '4.0s' },
      { name: 'Exploring', state: 'completed', duration: '12.5s' },
      { name: 'Testing', state: 'failed', duration: '1m 43s', description: 'Failed on critical unhandled server error 500' },
      { name: 'Analyzing', state: 'pending' },
      { name: 'Complete', state: 'pending' },
    ],
    events: [
      {
        id: 'evt_301',
        timestamp: '07:15:00',
        relativeTime: '00:00',
        type: 'system',
        description: 'Session dispatched targeting https://api-app.example.com/dashboard',
        status: 'info',
      },
      {
        id: 'evt_302',
        timestamp: '07:15:12',
        relativeTime: '00:12',
        type: 'navigation',
        description: 'Navigated to billing overview tab',
        status: 'success',
      },
      {
        id: 'evt_303',
        timestamp: '07:15:40',
        relativeTime: '00:40',
        type: 'network',
        description: 'GET /api/v2/orders?page=2 failed with HTTP 500 Internal Server Error',
        status: 'error',
      },
      {
        id: 'evt_304',
        timestamp: '07:15:45',
        relativeTime: '00:45',
        type: 'console',
        description: 'Uncaught TypeError: Cannot read properties of undefined (reading "records")',
        status: 'error',
      },
      {
        id: 'evt_305',
        timestamp: '07:16:00',
        relativeTime: '01:00',
        type: 'system',
        description: 'Test step aborted: Unhandled crash prevented DOM pagination reconciliation',
        status: 'error',
      },
    ],
    consoleLogs: [
      {
        id: 'c_301',
        timestamp: '07:15:45',
        level: 'error',
        source: 'billing-table.tsx:88',
        message: 'TypeError: Cannot read properties of undefined (reading "records")',
        stack: 'at BillingTable.render (billing-table.tsx:88)\n  at processChild (react-dom.production.min.js:14)',
      },
    ],
    networkLogs: [
      {
        id: 'net_301',
        timestamp: '07:15:40',
        method: 'GET',
        url: '/api/v2/orders?page=2',
        status: 500,
        statusText: 'Internal Server Error',
        duration: '1120ms',
        size: '120 B',
        type: 'fetch',
        hasError: true,
      },
    ],
    evidence: [
      {
        id: 'ev_301',
        title: 'Crash Screen & Missing Records Table',
        timestamp: '07:15:50',
        stepNumber: 3,
        stepName: 'Pagination Query',
        type: 'screenshot',
        caption: 'Application error boundary activated after 500 response from orders endpoint.',
        mockPreviewType: 'payment_error',
      },
    ],
    stats: {
      totalActions: 7,
      assertionsPassed: 2,
      assertionsFailed: 1,
      consoleErrors: 1,
      networkErrors: 1,
    },
  },

  {
    id: 'ses_live_1039',
    targetUrl: 'https://docs.example.com',
    targetHost: 'docs.example.com',
    prompt: 'Crawl documentation sidebar links, verify all internal anchor hrefs resolve with HTTP 200, and flag any 404 dead links or broken page anchors.',
    status: 'paused',
    currentStage: 'Exploring',
    startedAt: '5 hours ago',
    duration: '52s',
    viewport: {
      width: 1280,
      height: 800,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 HeadlessChrome/124.0.0.0 Safari/537.36 AgentOps/1.0',
    },
    stages: [
      { name: 'Understanding', state: 'completed', duration: '1.5s' },
      { name: 'Planning', state: 'completed', duration: '2.2s' },
      { name: 'Launching Browser', state: 'completed', duration: '3.8s' },
      { name: 'Exploring', state: 'active', duration: 'Paused at 52s', description: 'Operator paused exploration while reviewing discovered routes.' },
      { name: 'Testing', state: 'pending' },
      { name: 'Analyzing', state: 'pending' },
      { name: 'Complete', state: 'pending' },
    ],
    events: [
      {
        id: 'evt_401',
        timestamp: '05:10:00',
        relativeTime: '00:00',
        type: 'navigation',
        description: 'Navigated to https://docs.example.com',
        status: 'success',
      },
      {
        id: 'evt_402',
        timestamp: '05:10:25',
        relativeTime: '00:25',
        type: 'click',
        description: 'Crawled sidebar link [API Reference > Authentication]',
        status: 'success',
      },
      {
        id: 'evt_403',
        timestamp: '05:10:52',
        relativeTime: '00:52',
        type: 'system',
        description: 'Session execution paused by operator',
        status: 'warning',
      },
    ],
    consoleLogs: [],
    networkLogs: [
      {
        id: 'net_401',
        timestamp: '05:10:01',
        method: 'GET',
        url: '/',
        status: 200,
        statusText: 'OK',
        duration: '60ms',
        size: '14.2 KB',
        type: 'document',
        hasError: false,
      },
    ],
    evidence: [],
    stats: {
      totalActions: 4,
      assertionsPassed: 1,
      assertionsFailed: 0,
      consoleErrors: 0,
      networkErrors: 0,
    },
  },
];

export function getAllSessions(): BrowserSession[] {
  return PREVIEW_SESSIONS;
}

export function getSessionById(id: string): BrowserSession | undefined {
  return PREVIEW_SESSIONS.find((s) => s.id === id);
}
