import React, { useEffect, useMemo, useState } from 'react';
import { usePathname, Link } from '@/lib/router';
import { api, type ApiIssue } from '@/lib/api';
import { Badge, Button, Card, Input } from '@/components/ui';
import { ArrowLeft, AlertCircle, Bug, Search, Loader2 } from 'lucide-react';
import { groupRootIssues } from '@/lib/issue-groups';

const severityVariant = (severity: ApiIssue['severity']) => severity === 'critical' ? 'danger' : severity === 'high' ? 'warning' : severity === 'medium' ? 'info' : 'neutral';
const statusVariant = (status: ApiIssue['status']) => status === 'fixed' || status === 'closed' ? 'success' : status === 'open' ? 'danger' : 'neutral';

export default function IssuesPage() { const id=usePathname().split('/').filter(Boolean)[1]; return id ? <IssueDetail id={id}/> : <IssueList/>; }

function IssueList() {
  const [issues,setIssues]=useState<ApiIssue[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{api.listIssues().then(r=>setIssues(r.data)).catch(e=>setError(e instanceof Error?e.message:'Failed to load issues')).finally(()=>setLoading(false));},[]);
  const filtered=useMemo(()=>issues.filter(i=>!query.trim()||i.title.toLowerCase().includes(query.toLowerCase())||i.id.toLowerCase().includes(query.toLowerCase())),[issues,query]); const roots=useMemo(()=>groupRootIssues(filtered),[filtered]);
  return <div className="space-y-6"><div className="border-b border-border pb-3"><div className="flex items-center gap-2"><Bug className="w-5 h-5 text-rose-500"/><h1 className="text-2xl font-bold">Root Issues</h1></div><p className="text-sm text-muted-foreground mt-1">{roots.length} root causes across {filtered.length} raw failed-test symptoms from real QA runs.</p></div><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search issues..." leftIcon={<Search className="w-4 h-4"/>}/>{loading?<State text="Loading issues..." icon={<Loader2 className="animate-spin"/>}/>:error?<State text={error} icon={<AlertCircle/>}/>:roots.length===0?<State text="No issues detected."/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{roots.map(root=>{const issue=root.issues[0];return <Link key={root.key} href={`/issues/${issue.id}`} className="p-4 rounded-xl border border-border bg-surface hover:border-primary/30 transition-colors"><div className="flex justify-between gap-2"><span className="font-mono text-xs text-muted-foreground">{root.issues.length} affected runs/tests</span><Badge variant={severityVariant(issue.severity)}>{issue.severity}</Badge></div><h2 className="font-semibold text-sm mt-3">{root.rootCause}</h2><p className="text-xs text-muted-foreground mt-2">Run {issue.runId} · {issue.affectedUrl || 'Target URL unavailable'}</p><div className="mt-4"><Badge variant={statusVariant(issue.status)}>{issue.status}</Badge></div></Link>})}</div>}</div>;
}
function IssueDetail({id}:{id:string}) { const [issue,setIssue]=useState<ApiIssue|null>(null); const [error,setError]=useState<string|null>(null); useEffect(()=>{api.getIssue(id).then(r=>setIssue(r.data)).catch(e=>setError(e instanceof Error?e.message:'Failed to load issue'));},[id]); if(error)return <State text={error} icon={<AlertCircle/>}/>; if(!issue)return <State text="Loading issue..." icon={<Loader2 className="animate-spin"/>}/>; return <div className="space-y-6"><Link href="/issues"><Button variant="ghost" size="sm" leftIcon={<ArrowLeft className="w-4 h-4"/>}>Back to Issues</Button></Link><div><div className="flex gap-2 flex-wrap"><Badge variant={severityVariant(issue.severity)}>{issue.severity}</Badge><Badge variant={statusVariant(issue.status)}>{issue.status}</Badge></div><h1 className="text-2xl font-bold mt-2">{issue.title}</h1><p className="font-mono text-xs text-muted-foreground mt-1">{issue.id}</p></div><Card className="p-5 space-y-4"><p className="text-sm text-muted-foreground">{issue.description || 'No description provided.'}</p><div className="grid sm:grid-cols-2 gap-4 text-sm border-t border-border pt-4"><div><span className="text-xs text-muted-foreground">Run</span><p><Link className="font-mono text-primary" href={`/runs/${issue.runId}`}>{issue.runId}</Link></p></div><div><span className="text-xs text-muted-foreground">Created</span><p>{new Date(issue.createdAt).toLocaleString()}</p></div>{issue.affectedUrl&&<div className="sm:col-span-2"><span className="text-xs text-muted-foreground">Affected URL</span><p className="break-all font-mono text-xs">{issue.affectedUrl}</p></div>}</div></Card></div>; }
function State({text,icon}:{text:string;icon?:React.ReactNode}) { return <div className="py-12 text-center text-muted-foreground flex items-center justify-center gap-2">{icon}{text}</div>; }
